### ISSUE TITLE
Recall

### ISSUE THREAD

**Issue by djr2015** [Hanqer/deep-hough-transform#1]
I believe the calculation of the recall related to the EA score in `test.py` is incorrect (or at least inconsistent with how it is formulated in the paper). Here is a minimal working example to show that:
```
from basic_ops import *
from utils import caculate_precision, caculate_recall
from metric import EA_metric
import numpy as np 

total_precision = np.zeros(99)
total_recall = np.zeros(99)
nums_precision = 0
nums_recall = 0  

# 3 predictions, 4 ground truth lines
pred = np.array([[  2.      ,  -0.      , 372.15662 , 399.      ],
                 [ -0.      , 210.91667 , 399.      , 199.83333 ],
                 [ -0.      ,  24.555555, 399.      , 322.57407 ]])
gt = np.array([[ -0.      , 247.50629 , 399.      , 284.90628 ],
               [ -0.      , 205.      , 399.      , 205.      ],
               [ -0.      ,  16.582956, 399.      , 302.68295 ],
               [ -0.      , 159.68497 , 399.      , 125.78495 ]])

# Calculate precision and recall
# (as done in test.py)
for i in range(1, 100):
    p, num_p = caculate_precision(pred.tolist(), gt.tolist(), thresh=i*0.01)
    r, num_r = caculate_recall(pred.tolist(), gt.tolist(), thresh=i*0.01)
    total_precision[i-1] += p
    total_recall[i-1] += r
nums_precision += num_p
nums_recall += num_r

total_recall = total_recall / 4 # Total number of ground truth lines (vs. 298 in SEL test set)
total_precision = total_precision / nums_precision
f = 2 * total_recall * total_precision / (total_recall + total_precision)

# EA scores between predicted and ground truth lines
pred_lines = [Line(list(line)) for line in pred]
gt_lines = [Line(list(line)) for line in gt]

EA_matrix = np.zeros((3,4))
for pind, p in enumerate(pred_lines):
    for gind, g in enumerate(gt_lines):
        EA_matrix[pind,gind] = EA_metric(p,g)

# Rows = predictions, gt = columns
print(np.around(EA_matrix,3))
'''
array([[0.198, 0.212, 0.61 , 0.13 ],
       [0.612, 0.963, 0.27 , 0.661],
       [0.25 , 0.297, 0.909, 0.246]])
'''

# Recall for threshold 0.62 as per implementation
#(3 gts with EA > 0.62 with at least 1 pred line) / (4 gt lines) = 0.75
print(total_recall[61])

# Recall for threshold 0.62 as per description in paper
# equation 8 in paper: true positives =  2 preds whose best EA with gt is > 0.62 (2nd and 3rd rows)
TP = (np.max(EA_matrix,1) >= 0.62).sum()
# equation 9 in paper: false negatives = 1 gt  whose best EA with pred is < 0.62 (1st column)
FN = (np.max(EA_matrix,0) <  0.62).sum()

recall = TP/(TP + FN) 

# ( 2 / (2+1) ) = 0.67 
print(recall)  
```
I think the key issue is that a ground truth line, for a given threshold, may be neither a false negative nor count towards the total of true positives. The possibility of this happening is not taken into account in this implementation.

This happens if 
- it does not have the highest EA score with any given prediction and 
- there is at least one prediction with which it has an EA score higher than the threshold.

This is the case for the ground truth line in column #4 of `EA_matrix` in my example: 
- it does not have the highest EA score with any of the predictions (so it does not contribute to the total of true positives according to the paper definition)
- it has an EA score > 0.62 with prediction 2 (so it is not a false negative according to the paper definition)

It seems like in this implementation, the denominator of the recall is always equal to the number of ground truth lines, which assumes that ground truth lines are either TP or FN (according to the definition of recall)?

**Comment by zeakey** [comment]
Hi roberts, Thanks for your feedback.

After a discussion with @Hanqer , we believe that currently Eq8~10 in our paper is problematic.

The **recall** should be *number of GT lines with corresponding predicted lines* divided by *total number of GT lines*, and**precision** should be *number of predicted lines with corresponding GT lines* divided by *total number of predicted lines*.

Formally, precision and recall are defined as:
![TIM图片20200511115509](https://user-images.githubusercontent.com/6763078/81522792-5df94100-937e-11ea-9cf4-7c4fcb3dc7df.png)

**Comment by djr2015** [comment]
Hi Kai, thanks for your responsiveness!

I agree that your new proposed definitions of precision and recall are now consistent with their implementations. Looking at this more closely, however, it seems that equation (9)'s numerator may also include ground truth objects that do not have any correspondence with predictions. 

As an illustration, consider the ground truth line in column 4 in the EA_matrix variable of my example above. No predicted line is closest to it, but 1 prediction is closer than the threshold. This means it is included in the numerator of (9).

From my understanding, in object detection (where you calculate precision and recall with IoU between bounding boxes instead of EA between lines), you determine TP, FN, FP via the following matching strategy:

- For each prediction you find the ground truth with best IoU. If it's higher than a threshold, TP += 1, then *remove the ground truth match*, else FP += 1
- After going through each prediction, FN = # ground truths remaining (i.e. that weren't matched with any prediction)

Using this method, the ground truth line in column 4 I mentioned earlier should be FN because it will never be matched with a prediction.

**Comment by zeakey** [comment]
Yes I agree with you that there are cases that GT lines without a matched predicted line are considered as true-positive.
The oracle protocol should be "replace the IOU metric in object detection with our proposed EA-score". We will update the code and tables in the next release.

Even with this bug in our evaluation, we believe that the main conclusion of the paper is still true because the whole evaluation procedure is fair for all methods.

Any way this is indeed a bug in our implementation, thanks for pointing out that.
