### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by qgh1223** [Hanqer/deep-hough-transform#1]
How to train model in a new dataset?Where is the training code?

**Comment by Hanqer** [comment]
Due to privacy issues, the training scripts are not public now. We will consider releasing the training code latter.

**Comment by joshmyersdean** [comment]
Are there any updated plans to release the training code?

**Comment by Hanqer** [comment]
@joshmyersdean If you need the training code for non-commercial usage, please email me.

**Comment by qgh1223** [comment]
I need your training code.Please give the email address

**Comment by Hanqer** [comment]
@qgh1223 The email address can be avaiable from the ECCV paper (qhan_at_mail_dot_nankai_dot_edu_dot_cn) or my personal homepage (hqer_at_foxmail_dot_com). Please email me for non-commercial usage.

**Comment by qgh1223** [comment]
I have sent the email.But no response

**Comment by Hanqer** [comment]
Training code is open available.
