### ISSUE TITLE
Is it possible to run the code on CPU?

### ISSUE THREAD

**Issue by RocketFlash** [Hanqer/deep-hough-transform#10]
Hi! Thank you for your amazing work! 

Is it possible somehow to run your code on CPU ?

**Comment by Hanqer** [comment]
Thanks for your interest. 
We plan to develop the CPU version using AVX/SSE in the future. But currently, the CPU version is not supported.

**Comment by rokopi-byte** [comment]
Hi, any news on this? Inference on CPU would be great

**Comment by Govan111** [comment]
你好，请问有cpu的版本吗？目前感觉主要是deep hough安装需要依赖cuda，不知道是否可以有办法脱离这个依赖。
