### ISSUE TITLE
Failed to compile the C++ module due to incompatible gcc version.

### ISSUE THREAD

**Issue by carlsummer** [Hanqer/deep-hough-transform#11]
![image](https://user-images.githubusercontent.com/16281965/122491850-555e4a00-d017-11eb-8da0-d9a54d3edec5.png)

**Comment by carlsummer** [comment]
creating build/lib.linux-x86_64-3.8
g++ -pthread -shared -B /home/deploy/anaconda3/envs/yolov5_py38_cu102_conda/compiler_compat -L/home/deploy/anaconda3/envs/yolov5_py38_cu102_conda/lib -Wl,-rpath=/home/deploy/anaconda3/envs/yolov5_py38_cu102_conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/deploy/workspaces/CreepageDistance/models/_cdht/build/temp.linux-x86_64-3.8/deep_hough_cuda.o /home/deploy/workspaces/CreepageDistance/models/_cdht/build/temp.linux-x86_64-3.8/deep_hough_cuda_kernel.o -L/home/deploy/anaconda3/envs/yolov5_py38_cu102_conda/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-10.2/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.8/deep_hough.cpython-38-x86_64-linux-gnu.so
g++: error: /home/deploy/workspaces/CreepageDistance/models/_cdht/build/temp.linux-x86_64-3.8/deep_hough_cuda.o: No such file or directory
g++: error: /home/deploy/workspaces/CreepageDistance/models/_cdht/build/temp.linux-x86_64-3.8/deep_hough_cuda_kernel.o: No such file or directory
error: command 'g++' failed with exit status 1

**Comment by Hanqer** [comment]
Hi, I can't reproduce this error. Could you provide your g++ version, torch version?
Or maybe you can create a new clean environment to try again?

**Comment by zeakey** [comment]
@carlsummer The warning clearly tells you that the compiler you are using does not match the one used to compile PyTorch.

On my side I successfully compiled using `gcc 6.5.0`.

**Comment by carlsummer** [comment]
I don‘t know why，but， I solve it for switch conda envs

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
