### ISSUE TITLE
训练好的pth文件

### ISSUE THREAD

**Issue by Hshuqin** [Hanqer/deep-hough-transform#12]
作者您好，不知道您有没有训练的模型，可否发我一份，我test一下我的场景下的效果

**Comment by Hanqer** [comment]
The pre-trained model can be found in README.md with the URL.
If you want to test your own images, you can use the online demo to fastly verify the results.

**Comment by lucyLLLL** [comment]
online demo can't upload images?

**Comment by Hanqer** [comment]
@lucyLLLL  Sorry, it will recover within 24 hours. I will let you know when it is fixed to easily test your own images.

**Comment by Hshuqin** [comment]
the online demo can not upload




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanqer/deep-hough-transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月19日(星期六) 晚上10:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Hanqer/deep-hough-transform] 训练好的pth文件 (#12)





 
The pre-trained model can be found in README.md with the URL.
 If you want to test your own images, you can use the online demo to fastly verify the results.

**Comment by Hanqer** [comment]
@Hshuqin @lucyLLLL The online demo works now.

**Comment by Hshuqin** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanqer/deep-hough-transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 下午3:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanqer/deep-hough-transform] 训练好的pth文件 (#12)





 
@Hshuqin @lucyLLLL The online demo works now.
