### ISSUE TITLE
TorchScript

### ISSUE THREAD

**Issue by RocketFlash** [Hanqer/deep-hough-transform#15]
Hi! Is it possible to convert trained model to torchscript using ```torch.jit.trace``` or ```torch.jit.script``` ? I tried to convert trained model, it can be converted using ```torch.jit.trace``` but I can't save it. Saving gives an error:

```
RuntimeError: 
Could not export Python function call 'C_dht_Function'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:

```

**Comment by zeakey** [comment]
JIT compiler supports only bullion operators.
The `DHT` module is a C++ extension that cannot be recognized
 by the JIT compiler.

An ugly workaround here is to only convert the backbone and then fed the features to DHT module.

**Comment by RocketFlash** [comment]
@zeakey What if I reimplement ```DHT``` on PyTorch? How much do you think inference will slow down? If ```DHT``` will be on pure PyTorch, so it will be easy to convert the model to Torchscript and run the code on CPU, righ ?

**Comment by Hanqer** [comment]
@RocketFlash The naive version of DHT that does not parallel at all will slow down about 1000x.

**Comment by RocketFlash** [comment]
OMG :(

**Comment by RocketFlash** [comment]
Do you have pure torch implementation code? Could you share it if you have ?

**Comment by Hanqer** [comment]
@RocketFlash  Sorry, the implementation of the python version of DHT is only used in the early time of the project to verify the correctness and speedup. But I can't find it now. It just uses many loop blocks and you can refer to the OpenCV implementation (HT) on a single feature map.

**Comment by RocketFlash** [comment]
@Hanqer could you explain, why you're adding value from featuremap in cuda code?

```
float val = feat[imgIndex];
atomicAdd(&(output[outIndex]), val);
```

I didn't get an idea, why not just adding 1 in accumulator?

**Comment by Hanqer** [comment]
@RocketFlash  DHT accumulates the feature values instead of counting the quantized number. This is different from the original Hough Transform.  You can refer to Eq.(4) in the paper.

**Comment by RocketFlash** [comment]
Got it, thank you ! :)
