### ISSUE TITLE
line predict error

### ISSUE THREAD

**Issue by carlsummer** [Hanqer/deep-hough-transform#17]
![image](https://user-images.githubusercontent.com/16281965/123958041-29f83980-d9df-11eb-93cc-51864280e569.png)
why I predict image has points error by model 
本来应该
![image](https://user-images.githubusercontent.com/16281965/123958353-878c8600-d9df-11eb-83db-d3e9338d631e.png)

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/123963498-1bad1c00-d9e5-11eb-86af-7a6a503ce19c.png)

**Comment by carlsummer** [comment]
hough 不应该有2条长线吗，怎么只有2个点呢

**Comment by Hanqer** [comment]
hough空间的两个点，就代表了图像空间中的两条直线。 由于训练数据中都是自然场景图像，应用于您这种特殊场景，最好重新训练模型以获得更好的效果。
