### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by DevelMayCry-MrChen** [Hanqer/deep-hough-transform#19]
python setup.py build
python setup.py install --user

**Comment by zhoujianzx13** [comment]
I have the same problem. How can I solve it?

**Comment by DevelMayCry-MrChen** [comment]
> I have the same problem. How can I solve it?

use linux

**Comment by zhoujianzx13** [comment]
> > I have the same problem. How can I solve it?
> 
> use linux

thanks

**Comment by zeakey** [comment]
Hi please provide more detailed logs about your failed compilation.

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
