### ISSUE TITLE
Deep-hough?

### ISSUE THREAD

**Issue by Pzy-ss** [Hanqer/deep-hough-transform#2]
Great work！ However， I have trouble installing deep-hough (in Windows10, with Visual Studio 2019)，Could you please give more details about the installation? Thank you!

**Comment by Hanqer** [comment]
Currently, this work was carried on Ubuntu16.04. And it works well on Ubuntu18.04 as well. The details system environment are listed as:
```
Ubuntu16.04
CUDA10.0 (you may need an Nvidia GPU card which supports sm_60)
PyTorch1.2
```
Then the following commands will install the deep-hough.
```
cd deep-hough-transform
cd model/_cdht
python setup.py build 
python setup.py install --user
```
Sorry that this work was not tested on Windows10 system.

**Comment by Pzy-ss** [comment]
Thank you for your prompt reply！

**Comment by HassanBinHaroon** [comment]
@Pzy-ss  Take a look at the following repository too. Hopefully there are no installation errors. 

https://github.com/HassanBinHaroon/deep-hough-transform
