### ISSUE TITLE
Data preprocessing problems

### ISSUE THREAD

**Issue by yanconglin** [Hanqer/deep-hough-transform#2]
HI, Hanqer,
Nice work, thanks for sharing.
encountered two problems when pre-processing the dataset:
(1). img 0338: File "prepare_data_JTLEE.py", line 105, in <module>
    hough_space_label[theta, r] += 1
IndexError: index 118 is out of bounds for axis 1 with size 100
(2).  img 0336: coordinates=[0,0,0,0]
File "basic_ops.py", line 17, in __init__
    assert coordinates[0]!=coordinates[2] or coordinates[1]!=coordinates[3]
AssertionError.

Tried to unzip the dataset again, and the errors are still there. Was wondering if there are any mistakes when releasing the code.
Looking forward to your reply, and thanks a lot.

**Comment by Hanqer** [comment]
Hi,
The data scripts were updated today. Please pull the new version and run the script again. If you still encounter the above problems, please contact me.
