### ISSUE TITLE
deep_hough_cuda_kernel.o: No such file or directory

### ISSUE THREAD

**Issue by xuyichengyy** [Hanqer/deep-hough-transform#21]
Thank you for help me solve the last problem，but I get a new error,the error is below
`g++: error: /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda_kernel.o: No such file or directory
error: command 'g++' failed with exit status 1
`
and gcc version is 5.4.0

**Comment by Hanqer** [comment]
Could you provide a more detailed error log? There are so many reasons cause the missing of .o files.

**Comment by xuyichengyy** [comment]
> Could you provide a more detailed error log? There are so many reasons cause the missing of .o files.
This is all the running information

` python setup.py install
running install
running bdist_egg
running egg_info
writing deep_hough.egg-info/PKG-INFO
writing dependency_links to deep_hough.egg-info/dependency_links.txt
writing top-level names to deep_hough.egg-info/top_level.txt
reading manifest file 'deep_hough.egg-info/SOURCES.txt'
writing manifest file 'deep_hough.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'deep_hough' extension
Emitting ninja build file /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
g++ -pthread -shared -L/home/cver0/anaconda3/envs/seline/lib -Wl,-rpath=/home/cver0/anaconda3/envs/seline/lib,--no-as-needed /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda.o /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda_kernel.o -L/home/cver0/anaconda3/envs/seline/lib/python3.6/site-packages/torch/lib -L:/usr/local/cuda/lib64 -L/home/cver0/anaconda3/envs/seline/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -lpython3.6m -o build/lib.linux-x86_64-3.6/deep_hough.cpython-36m-x86_64-linux-gnu.so
g++: error: /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda_kernel.o: No such file or directory
error: command 'g++' failed with exit status 1
`

**Comment by xuyichengyy** [comment]
> Could you provide a more detailed error log? There are so many reasons cause the missing of .o files.
This is all the running information

` python setup.py install
running install
running bdist_egg
running egg_info
writing deep_hough.egg-info/PKG-INFO
writing dependency_links to deep_hough.egg-info/dependency_links.txt
writing top-level names to deep_hough.egg-info/top_level.txt
reading manifest file 'deep_hough.egg-info/SOURCES.txt'
writing manifest file 'deep_hough.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'deep_hough' extension
Emitting ninja build file /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
g++ -pthread -shared -L/home/cver0/anaconda3/envs/seline/lib -Wl,-rpath=/home/cver0/anaconda3/envs/seline/lib,--no-as-needed /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda.o /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda_kernel.o -L/home/cver0/anaconda3/envs/seline/lib/python3.6/site-packages/torch/lib -L:/usr/local/cuda/lib64 -L/home/cver0/anaconda3/envs/seline/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -lpython3.6m -o build/lib.linux-x86_64-3.6/deep_hough.cpython-36m-x86_64-linux-gnu.so
g++: error: /home/cver0/cxy/deep-hough-transform-master/model/_cdht/build/temp.linux-x86_64-3.6/deep_hough_cuda_kernel.o: No such file or directory
error: command 'g++' failed with exit status 1
`

**Comment by xuyichengyy** [comment]
This is all running information 
![image](https://user-images.githubusercontent.com/49033074/132801165-723f1181-9cda-496b-b23a-3414b9696015.png)

**Comment by Hanqer** [comment]
It is weird that the .o file is not built by NVCC first.  Could you run "python setup.py clean -all" and then try it again?

**Comment by xuyichengyy** [comment]
The problem has been solved. Thank you very much. Happy Teachers' Day

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
