### ISSUE TITLE
test_sel.py和test_nkl.py找不到gt_path路径 

### ISSUE THREAD

**Issue by Hou12378** [Hanqer/deep-hough-transform#23]
![QQ截图20210911145725](https://user-images.githubusercontent.com/72130551/132939600-49d910fa-32cc-42b8-88ed-fa0c6083797b.jpg)
①在test_nkl.py中gt_path路径下JTLEE_resize_100_100文件夹中不含有.txt的文件 。
![QQ截图20210911145804](https://user-images.githubusercontent.com/72130551/132939602-d6cf1e54-1623-4c5f-b5b6-eb3d68f04a31.jpg)
②在test_sel.py的gt_path路径下中找不到SL5K_resize_100_100这个文件夹

**Comment by Hanqer** [comment]
实际上这两句话是无效的，gt_path通过args.gt传入，参考Readme调用形式。

**Comment by Hou12378** [comment]
这样的话它是报错 的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanqer/deep-hough-transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanqer/deep-hough-transform] test_sel.py和test_nkl.py找不到gt_path路径  (#23)





 
实际上这两句话是无效的，gt_path通过args.gt传入，参考Readme调用形式。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hou12378** [comment]
这样的话它是报错 的。


当更改到含有.txt的文件夹下时，结果是错的


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Hanqer/deep-hough-transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanqer/deep-hough-transform] test_sel.py和test_nkl.py找不到gt_path路径  (#23)





 
实际上这两句话是无效的，gt_path通过args.gt传入，参考Readme调用形式。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hanqer** [comment]
因为后面有 gt_path = arg.gt   所以这两句话可以直接删掉，也可以保留，但不会报错。 如果出现No such file or directory错误，应该是arg.gt有问题

**Comment by Hanqer** [comment]
如有错误，请附error log和目录结构，我这边验证没有问题。

**Comment by Hou12378** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanqer/deep-hough-transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanqer/deep-hough-transform] test_sel.py和test_nkl.py找不到gt_path路径  (#23)





 
如有错误，请附error log和目录结构，我这边验证没有问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by samsunq** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Hanqer/deep-hough-transform" ***@***.***&gt;; 发送时间:&nbsp;2021年9月11日(星期六) 下午3:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Hanqer/deep-hough-transform] test_sel.py和test_nkl.py找不到gt_path路径 (#23) 如有错误，请附error log和目录结构，我这边验证没有问题。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



> ![QQ截图20210911145725](https://user-images.githubusercontent.com/72130551/132939600-49d910fa-32cc-42b8-88ed-fa0c6083797b.jpg) ①在test_nkl.py中gt_path路径下JTLEE_resize_100_100文件夹中不含有.txt的文件 。 ![QQ截图20210911145804](https://user-images.githubusercontent.com/72130551/132939602-d6cf1e54-1623-4c5f-b5b6-eb3d68f04a31.jpg) ②在test_sel.py的gt_path路径下中找不到SL5K_resize_100_100这个文件夹

您好 不知道您复现代码的时候有没有找到deep hough那个wheel；如果有是否可以分享一下。感谢感谢，好人一生平安。’
