### ISSUE TITLE
Build CUDA extensions.

### ISSUE THREAD

**Issue by zhouzhonghe** [Hanqer/deep-hough-transform#24]
Making this package is driving me crazy

**Comment by samsunq** [comment]
can't download the deep-hough；hao ren yi sheng ping an!

**Comment by samsunq** [comment]
> Making this package is driving me crazy

应该是咱们环境没有搭建好 所以没有生产deep hough这个py

**Comment by sdustzcm1995** [comment]
有搭配好的老哥给透露一下啊

**Comment by zeakey** [comment]
<https://github.com/vlkit/deephough>

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform

**Comment by samsunq** [comment]
thxs a lot, it would be very helpful for my question.
________________________________
发件人: Hassan Bin Haroon ***@***.***>
发送时间: 2022年8月11日 10:07
收件人: Hanqer/deep-hough-transform ***@***.***>
抄送: samsunq ***@***.***>; Comment ***@***.***>
主题: Re: [Hanqer/deep-hough-transform] Build CUDA extensions. (#24)


Take a look at the following repository too.

https://github.com/HassanBinHaroon/deep-hough-transform

―

**Comment by fishyupp** [comment]
有配置好的老哥吗？在线等一个方法

**Comment by HassanBinHaroon** [comment]
Kindly follow the instructions on repo. I hope the question will be
answered that way.

**Comment by fishyupp** [comment]
When I run the code  " !python forward.py --model dht_r50_nkl_d97b97138.pth --tmp results  " , this problem occurs. 
<img width="944" alt="DHT问题" src="https://user-images.githubusercontent.com/57426645/206696250-3bfc522e-6df5-4975-aba0-3d69c0a9b609.png">
Hope someone can help me.
