### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by zhizhz** [Hanqer/deep-hough-transform#26]
作者您好，我最近也在尝试复现您这篇论文，但是在环境中遇到些许问题，目前就是我的python版本3.7和Ubuntu系统版本16.4 但是cuda版本和anaconda版本无法确定，之前尝试下载过cuda11.0后提示报错，请问您当时运行的这些cuda和anaconda的版本是什么版本的呢

**Comment by zeakey** [comment]
我们这份代码对 cuda 版本依赖不是很强，应该 cuda10/11 都可以的。你先确定你的 cuda 版本。
你配置环境遇到问题应该 post 你详细的 log，不然这里没法帮到你。
