### ISSUE TITLE
是否可以上传一下deep hough的包或者轮子？实在找不到

### ISSUE THREAD

**Issue by samsunq** [Hanqer/deep-hough-transform#27]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanqer/deep-hough-transform"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanqer/deep-hough-transform] test_sel.py和test_nkl.py找不到gt_path路径  (#23)

 
如有错误，请附error log和目录结构，我这边验证没有问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

_Originally posted by @Hou12378 in https://github.com/Hanqer/deep-hough-transform/issues/23#issuecomment-917359311_

**Comment by zeakey** [comment]
wheel 依赖于cuda环境，因此我们这边编译的你不一定能用。你可以下载源代码自己编译一下，readme里面写了怎么编译：
```
cd model/_cdht
python setup.py build 
python setup.py install --user
```

**Comment by zeakey** [comment]
See <https://github.com/vlkit/deephough> for buiding details and pre-built wheels.
