### ISSUE TITLE
deep hough安装环境

### ISSUE THREAD

**Issue by sdustzcm1995** [Hanqer/deep-hough-transform#28]
您好！请问您CUDA、CUDNN和torch的版本具体是啥？安装deep hough一直在出错，已经更新了VC版本了，又报错了

**Comment by Hanqer** [comment]
您好，cuda9及以上， 对应版本的cudnn torch1.3及以上都可以顺利编译的。您需要使用ubuntu系统进行编译运行，目前代码不支持windows系统

**Comment by sdustzcm1995** [comment]
感谢！原来是系统的事
