### ISSUE TITLE
Can it run without a GPU and CUDA?

### ISSUE THREAD

**Issue by LinkChain** [Hanqer/deep-hough-transform#3]
Can my laptop run it without a GPU and CUDA?

**Comment by Hanqer** [comment]
Hi, currently, this code only supports to train and test on the Nvidia GPU card. The deep-hough has only a GPU implementation.
If you want to test your own data for non-commercial usage, you can go to our [online demo](http://mc.nankai.edu.cn/dht) of this project.

**Comment by HassanBinHaroon** [comment]
@LinkChain Take a look at the following repository too. You can do much without own GPU now. 

https://github.com/HassanBinHaroon/deep-hough-transform
