### ISSUE TITLE
Warning: image /home/zhaohanguang/deep-hough-transform/deep-hough-transform/data/NKL/train.jpg doesnt exist!

### ISSUE THREAD

**Issue by ZZZHG** [Hanqer/deep-hough-transform#32]
Warning: image /home/zhaohanguang/deep-hough-transform/deep-hough-transform/data/NKL/train.jpg doesnt exist!
I use your dataset NKL ,how can i do for nkl?

![图片](https://user-images.githubusercontent.com/86472549/146150546-89e2debb-ed63-4bf7-93fa-563a5d24cd16.png)

**Comment by ZZZHG** [comment]
![图片](https://user-images.githubusercontent.com/86472549/146153453-108d6c50-c7ea-4862-bf77-d6aaa9bb1bac.png)
This is mine?
Is is ok?
Thanks

**Comment by ZZZHG** [comment]
![图片](https://user-images.githubusercontent.com/86472549/146153963-3eefd652-00cd-408e-a169-9352a01b2fce.png)
Visualization must?

**Comment by zeakey** [comment]
I didn't even get what your problem is. By the way, the visualization is not necessary.

**Comment by ZZZHG** [comment]
> I didn't even get what your problem is. By the way, the visualization is not necessary.

Thanks

**Comment by ZZZHG** [comment]
What should the directory of the NKL dataset look like？
Must idx？

**Comment by ZZZHG** [comment]
![图片](https://user-images.githubusercontent.com/86472549/149619989-4768f639-3ce8-4c60-b6b0-708ad5ee300e.png)
 nn.functional.upsample is necessary for train?
What can I do for this issue?

**Comment by Hanqer** [comment]
The above issue is a user warning. you can ignore and still use it, or you can change the nn.funtional.upsample to nn.Upsample as recommended.
