### ISSUE TITLE
unable to download NKL dataset

### ISSUE THREAD

**Issue by Ali-Es95** [Hanqer/deep-hough-transform#37]
Thank you for your nice work,
I am facing a problem with downloading the NKL dataset, i tried as well different browsers and it keep on falling when i try to download.
i tried it on google colab as well and it showing the same problem.

> --2022-04-03 16:36:54--  http://data.kaizhao.net/projects/deep-hough-transform/NKL.zip
Resolving data.kaizhao.net (data.kaizhao.net)... 104.21.43.242, 172.67.190.95, 2606:4700:3030::6815:2bf2, ...
Connecting to data.kaizhao.net (data.kaizhao.net)|104.21.43.242|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://data.kaizhao.net/projects/deep-hough-transform/NKL.zip [following]
--2022-04-03 16:36:54--  https://data.kaizhao.net/projects/deep-hough-transform/NKL.zip
Connecting to data.kaizhao.net (data.kaizhao.net)|104.21.43.242|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 581179759 (554M) [application/zip]
Saving to: ‘NKL.zip’

> NKL.zip               1%[                    ]   6.53M  32.4KB/s    in 4m 3s   

> 2022-04-03 16:40:59 (27.5 KB/s) - Connection closed at byte 6842545. Retrying.

> --2022-04-03 16:41:00--  (try: 2)  https://data.kaizhao.net/projects/deep-hough-transform/NKL.zip
Connecting to data.kaizhao.net (data.kaizhao.net)|104.21.43.242|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 581179759 (554M) [application/zip]
Saving to: ‘NKL.zip’

> NKL.zip               0%[                    ]   1.19M  53.4KB/s    eta 5h 55m ^C

Thanks, you for your time

**Comment by Hanqer** [comment]
Maybe the server is unstable. I can download it via browser and wget. 
I upload the dataset to google drive, you can download it: [Google Drive](https://drive.google.com/file/d/1GKp_AhwJouHas1ZDAa2YAG6ASqXBvu3-/view?usp=sharing)

**Comment by Ali-Es95** [comment]
Thank you, i got it

**Comment by zeakey** [comment]
@Ali-Es95 Which region are you in? Are you in the north America or Europe? Actually the data is stored on Alibaba cloud service in Shanghai.

**Comment by Ali-Es95** [comment]
@zeakey Yes, in Germany

**Comment by HassanBinHaroon** [comment]
@Ali-Es95  Take a look at the following repository too. It downloads both NKL and SEL datasets

https://github.com/HassanBinHaroon/deep-hough-transform
