### ISSUE TITLE
论文算法相关问题？

### ISSUE THREAD

**Issue by zhizhz** [Hanqer/deep-hough-transform#39]
老师您好，目前我在看论文和代码的时候有以下问题？
您深度霍夫变换是对这个图片的所有像素点进行的直线转换吗，就是我对论文里深度霍夫算法的理解是将线转换成参数空间的点，但是这个线我们是怎么得到的呢？
另外就是深度霍夫变换到参数空间还会进行训练吗？还是说当转换到参数空间之后直接与label进行loss的计算呢？

**Comment by Hanqer** [comment]
你好, 深度霍夫变换的本质是将每条直线的特征转化到参数空间中，但是具体实现如文中和代码所示的每个像素点对其可能潜在的直线进行投票，也就是遍历每个像素点可能存在的直线参数，对该点特征投票到参数空间。 该过程对图像中该量化尺度下的所有可能直线进行了转换，即传统霍夫变换中“霍夫投票（Hough voting）”的过程。
深度霍夫变换进行空间变换后，仍然进行特征聚合操作，如CTX和多尺度信息的聚合，是参与到端到端训练中的，最后再参数空间进行loss计算，并反向传播。

**Comment by zhizhz** [comment]
谢谢老师的解答，传统霍夫变换的过程是在CNN深度提取之后也就是和深度霍夫变换一起进行的话，进行所有像素点的投票之后这个特征聚合是什么过程呢，因为一般的霍夫变换投票过程好像只是投票最后之后大于设定的值就认定其为直线边缘
并且之后的上下文感知线检测器的话是否相同提取尺寸下不同通道提取的直线进行的目标线和其周围线的参数之后的卷积核运算呢？
最后就是您深度霍夫的模块是C++语言写成的，那传统霍夫变换的模块也是在那里吗？

**Comment by Hanqer** [comment]
@zhizhz 传统霍夫变换变换的不是CNN特征，特征聚合也不是传统霍夫变换的特性，这些都是我们在文章提出的DHT全新流程。 关于传统霍夫变换的霍夫投票过程，您可以通过opencv的代码深入学习，传统霍夫变换时通过阈值来进行的，而本文的方法是通过CTX和语义特征来进行判断的，您可以进一步阅读我们文章方法的一章来深入理解。

传统霍夫变换的实现取决于实现版本，opencv开源的代码是C++实现。 我们的深度霍夫变换模块由C++和CUDA编写。

**Comment by zhizhz** [comment]
谢谢老师解答
