### ISSUE TITLE
有关论文的一些问题

### ISSUE THREAD

**Issue by xuecheng990531** [Hanqer/deep-hough-transform#41]
作者您好，在阅读论文的时候遇到了一些问题，想找您请教一下：

1. 请问之前issues提到的“遍历每个像素点可能存在的直线参数，对该点特征投票到参数空间可能存在的直线进行投票”是什么意思，这跟论文中说的将可能存在直线上的所有特征汇聚起来转换到参数空间好像不太一样。
2. DHT模块的反向传播部分是不是没有可供训练的参数，只是简单的映射？

**Comment by Hanqer** [comment]
您好，
1. 这两者在确定的量化尺度下是等价的，您可以参考传统霍夫变换的OpenCV实现去深入理解。 每条直线投影到一个量化的点上，等价于每个像素点根据量化尺度遍历去分别累加到对应的点上。
2. DHT的前向传播是无参数的，只是对特征进行投影，改变了空间分布。 同理反向传播也是无参数的，backward只是把梯度回传，用于链式求导传递。

**Comment by xuecheng990531** [comment]
谢谢老师，对于第一条是不是可以这么理解：对feature map的每一个像素进行传统霍夫变换，论文中的相加对应着传统的累加器的操作呢？最后利用得到的霍夫空间经过两次卷积（CTX）来聚集上下文信息。

**Comment by Hanqer** [comment]
@xuecheng990531 与传统霍夫变换不同的地方在于传统霍夫变换操作的边缘激活图或者其他属性图，深度霍夫变换是对feature进行累加，对应到网络中一个forward backward完整模块。

**Comment by xuecheng990531** [comment]
@Hanqer 是对所有的特征进行霍夫变换，然后对那些特征在直线上的进行累加到参数空间是吗？

**Comment by xuecheng990531** [comment]
嗯嗯好的老师，我还想咨询一下：特征空间中可能的直线参数 r 和 theta 是用霍夫变换还是别的方式确定的？
