### ISSUE TITLE
g++版本问题

### ISSUE THREAD

**Issue by icelemon233** [Hanqer/deep-hough-transform#42]
作者您好。在安装deep-hough库时出现了以下的错误提示：
RuntimeError: The current installed version of g++ (9.3.0) is greater than the maximum required version by CUDA 10.2 (8.0.0). Please make sure to use an adequate version of g++ (>=5.0.0, <=8.0.0).
请问这是pytorch版本导致的错误吗？如何修复？等待您的反馈。

**Comment by zeakey** [comment]
看报错信息：`g++` 版本太高了，`cuda10` 要求 `5.0.0 <= gcc <= 8.0.0`。
要么升级 `cuda`，要么降级 `gcc`。
