### ISSUE TITLE
提示g++问题

### ISSUE THREAD

**Issue by icelemon233** [Hanqer/deep-hough-transform#43]
作者您好。在安装deep-hough库时，出现了以下提示：
The current installed version of g++ (9.3.0) is greater than the maximum required version by CUDA 10.2 (8.0.0). Please make sure to use an adequate version of g++ (>=5.0.0, <=8.0.0).
请问应该如何解决？期待您的回复。

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
