### ISSUE TITLE
使用NKL数据集进行Test提示GPU内存不足

### ISSUE THREAD

**Issue by icelemon233** [Hanqer/deep-hough-transform#44]
单块GPU处于空闲状态，且为一块RTX2080Ti。
提示：
File "forward.py", line 81, in main
    total_time = test(test_loader, model, args)
  File "forward.py", line 102, in test
    key_points = model(images)
……
……
RuntimeError: CUDA error: out of memory
请问如何解决？感谢。

**Comment by HassanBinHaroon** [comment]
@icelemon233  Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
