### ISSUE TITLE
Data processing codes for NKL dataset.

### ISSUE THREAD

**Issue by PengfeiRen96** [Hanqer/deep-hough-transform#5]
Hi, thanks for sharing your work. It is great work. Can you provide a preprocessing code for the dataset SL5K.

**Comment by Hanqer** [comment]
I will release the code for SL5k soon.

**Comment by PengfeiRen96** [comment]
Thank you for your reply and look forward to your code.

**Comment by Hanqer** [comment]
We support NKL dataset now. You can pull the latest code including training scripts and data preprocessing scripts for your experiments. If you have any questions about data processing, please re-open this issue.
