### ISSUE TITLE
论文代码最后结果

### ISSUE THREAD

**Issue by zhizhz** [Hanqer/deep-hough-transform#51]
老师您好，我最近跑了一遍您原先的代码发现评价指标如下所示：
Mean P: 0.63580007390983
Mean R: 0.7869525443110351
Mean F: 0.7033466363096472
F@0.95: 0.4367617316136169
而这并不能达到您公布的pth文件中所跑出来的
Mean P: 0.6842166184936662
Mean R: 0.766064417762531
Mean F: 0.7228304458943596
F@0.95: 0.46145579498809
请问这样的波动是正常的吗？
我的实验环境是2080ti PyTorch  1.7.0 ubuntu18.04 Cuda  11.0

**Comment by zhizhz** [comment]
其中数据集都是NKL进行的验证

**Comment by Hanqer** [comment]
论文中的结果是多次实验的平均值，一般不会偏差这么大，我的实验环境是TITAN XP， PyTorch1.2， cuda10.2

**Comment by zhizhz** [comment]
好的，谢谢老师的解答
