### ISSUE TITLE
The pretrained model used in online demo 

### ISSUE THREAD

**Issue by Sharenal** [Hanqer/deep-hough-transform#7]
Hello, I read your paper and git, It is a great work! Can you provide the model used in online demo? Thanks for sharing!

**Comment by zeakey** [comment]
The model used in our online demo is available [here](http://data.kaizhao.net/projects/deep-hough-transform/dht_r50_nkl_d97b97138.pth). It was pretrained on the [NKL dataset](http://kaizhao.net/nkl) .
