### ISSUE TITLE
loss function

### ISSUE THREAD

**Issue by Stinky-Tofu** [Hanqer/deep-hough-transform#9]

**Comment by Hanqer** [comment]
I know that there exists potential problems in optimization because of the unbalanced data. Actually, the loss function is not the main contribution of the paper. You can try it yourself.

**Comment by sqrt23** [comment]
@Stinky-Tofu 当你发现一个东西有缺陷并且随便一个小的trick就能解决的时候，特别是在 CV 这种内卷严重竞争激烈的行业，原因大概率不是“作者没有想到”。

具体对这个论文而言，正负样本均衡，乃至过多的数据扩增一定是能提升性能的，但是为什么作者就不做呢？我估计原因显然不是作者没想到，而是作者就不想做。我能猜测到的原因大概有二：

1. 这种 tricks 即便是提升了性能，放到论文里也是减分项。论文里放太多与主要 contribution 无关的 tricks强行提升性能，只会让审稿人觉得方法是拼凑的，印象会很差；

2. 作为一个领域比较早的一两个paper，同时还提出了一个数据集，肯定是希望更多的人能够沿着这条线做下去，增加论文影响力。那么显然 baseline 就不能刷的太高，让后面的人没法做。高明的做法是把 baseline 做的很低，乃至于故意留一些可以修补之处，让后面的人有很多可以提升性能（灌水）的余地。
